import { css, customElement, html, nothing, repeat, state } from "@umbraco-cms/backoffice/external/lit";
import { UmbLitElement } from "@umbraco-cms/backoffice/lit-element";
import type { ManifestDashboard } from "@umbraco-cms/backoffice/dashboard";
import { UMB_AUTH_CONTEXT } from "@umbraco-cms/backoffice/auth";
import { UMB_NOTIFICATION_CONTEXT } from "@umbraco-cms/backoffice/notification";
import { umbConfirmModal } from "@umbraco-cms/backoffice/modal";
import {
  deleteTemplate, duplicateTemplate, exportTemplate, fetchFonts, fetchHealth, fetchTemplates,
  hrefForCreate, hrefForDashboard, hrefForTemplate, importTemplate,
  notifyTemplatesChanged, type TokenGetter,
} from "../api/dynamic-images-api.js";
import type { DiFont, DiHealthReport, DiTemplateSummary } from "../api/types.js";

/** The section's landing page: what exists, whether it is healthy, and the way in to everything. */
@customElement("di-overview-dashboard")
export class DiOverviewDashboardElement extends UmbLitElement {
  /** Assigned by the extension host once the dashboard is instantiated. */
  manifest?: ManifestDashboard;

  #authContext?: typeof UMB_AUTH_CONTEXT.TYPE;
  #notificationContext?: typeof UMB_NOTIFICATION_CONTEXT.TYPE;

  @state()
  private _templates: DiTemplateSummary[] = [];

  @state()
  private _fonts: DiFont[] = [];

  @state()
  private _health?: DiHealthReport;

  @state()
  private _loading = true;

  @state()
  private _importing = false;

  @state()
  private _pasteJson = "";

  @state()
  private _showPaste = false;

  constructor() {
    super();

    this.consumeContext(UMB_NOTIFICATION_CONTEXT, (context) => {
      this.#notificationContext = context;
    });

    this.consumeContext(UMB_AUTH_CONTEXT, (context) => {
      this.#authContext = context;
      if (context) void this.#load();
    });
  }

  #getToken: TokenGetter = () => this.#authContext?.getLatestToken();

  async #load() {
    this._loading = true;

    try {
      const [templates, fonts, health] = await Promise.all([
        fetchTemplates(this.#getToken),
        fetchFonts(this.#getToken).catch(() => [] as DiFont[]),
        fetchHealth(this.#getToken).catch(() => undefined),
      ]);

      this._templates = templates;
      this._fonts = fonts;
      this._health = health;
    } catch (error) {
      this.#notify("danger", "The dashboard could not be loaded", error);
    } finally {
      this._loading = false;
    }
  }

  #notify(colour: "positive" | "warning" | "danger", headline: string, error?: unknown) {
    const message = error instanceof Error ? error.message : "";
    if (error) console.error("[DynamicImages]", headline, error);

    this.#notificationContext?.peek(colour, { data: { headline, message } });
  }

  async #importPasted() {
    if (!this._pasteJson.trim()) return;

    this._importing = true;

    try {
      await importTemplate(this._pasteJson, "create", this.#getToken);
      this.#notify("positive", "Imported");

      this._pasteJson = "";
      this._showPaste = false;

      notifyTemplatesChanged();
      await this.#load();
    } catch (error) {
      this.#notify("danger", "That could not be imported", error);
    } finally {
      this._importing = false;
    }
  }

  async #duplicate(template: DiTemplateSummary) {
    try {
      await duplicateTemplate(template.key, this.#getToken);
      this.#notify("positive", `'${template.name}' duplicated`);

      notifyTemplatesChanged();
      await this.#load();
    } catch (error) {
      this.#notify("danger", "The template could not be duplicated", error);
    }
  }

  async #delete(template: DiTemplateSummary) {
    await umbConfirmModal(this, {
      headline: `Delete '${template.name}'?`,
      content: "Images already generated by it stay in the media library; nothing new will be generated.",
      confirmLabel: "Delete",
      color: "danger",
    });

    try {
      await deleteTemplate(template.key, this.#getToken);
      this.#notify("positive", `'${template.name}' deleted`);

      notifyTemplatesChanged();
      await this.#load();
    } catch (error) {
      this.#notify("danger", "The template could not be deleted", error);
    }
  }

  async #export(template: DiTemplateSummary) {
    try {
      const blob = await exportTemplate(template.key, this.#getToken);
      const url = URL.createObjectURL(blob);

      const link = document.createElement("a");
      link.href = url;
      link.download = `${template.alias}.json`;
      link.click();

      URL.revokeObjectURL(url);
    } catch (error) {
      this.#notify("danger", "The template could not be exported", error);
    }
  }

  render() {
    if (this._loading) return html`<div class="state"><uui-loader></uui-loader></div>`;

    return html`
      <umb-body-layout headline="Dynamic Images">
        ${this.#renderStats()} ${this.#renderHealth()} ${this.#renderTemplates()}
      </umb-body-layout>
    `;
  }

  #renderStats() {
    const issues = this._health?.issues.filter((issue) => issue.severity !== "info").length ?? 0;

    return html`
      <div class="stats">
        ${this.#renderStat("Templates", this._templates.length, "icon-brush")}
        ${this.#renderStat("Fonts", this._fonts.length, "icon-font")}
        ${this.#renderStat("Issues", issues, issues > 0 ? "icon-alert" : "icon-check", issues > 0)}
        ${this.#renderStat(
          "Generation",
          this._health?.isEnabled === false ? "Off" : "On",
          "icon-power",
          this._health?.isEnabled === false,
        )}
      </div>
    `;
  }

  #renderStat(label: string, value: string | number, icon: string, warn = false) {
    return html`
      <uui-box class="stat ${warn ? "warn" : ""}">
        <uui-icon name=${icon}></uui-icon>
        <div class="stat-value">${value}</div>
        <div class="stat-label">${label}</div>
      </uui-box>
    `;
  }

  #renderHealth() {
    const issues = this._health?.issues.filter((issue) => issue.severity !== "info") ?? [];
    if (issues.length === 0) return nothing;

    return html`
      <uui-box headline="Needs attention">
        <uui-table>
          ${repeat(
            issues.slice(0, 8),
            (issue, index) => `${issue.code}-${index}`,
            (issue) => html`
              <uui-table-row>
                <uui-table-cell style="width: 90px">
                  <uui-tag color=${issue.severity === "error" ? "danger" : "warning"} look="secondary">
                    ${issue.severity}
                  </uui-tag>
                </uui-table-cell>
                <uui-table-cell>
                  ${issue.templateName ? html`<strong>${issue.templateName}</strong> — ` : nothing}${issue.message}
                </uui-table-cell>
              </uui-table-row>
            `,
          )}
        </uui-table>
        <uui-button look="secondary" href=${hrefForDashboard("health")} label="See all issues">See all</uui-button>
      </uui-box>
    `;
  }

  #renderTemplates() {
    return html`
      <uui-box headline="Templates">
        <div slot="header-actions" class="header-actions">
          <uui-button
            look="secondary"
            label="Paste a template"
            @click=${() => {
              this._showPaste = !this._showPaste;
            }}>
            Import JSON
          </uui-button>
          <uui-button look="primary" color="positive" href=${hrefForCreate()} label="Create a template">
            Create
          </uui-button>
        </div>

        ${this._showPaste ? this.#renderPaste() : nothing}
        ${this._templates.length === 0 ? this.#renderEmpty() : this.#renderCards()}
      </uui-box>
    `;
  }

  #renderPaste() {
    return html`
      <div class="paste">
        <uui-textarea
          label="Template JSON"
          placeholder="Paste an exported template"
          rows="6"
          .value=${this._pasteJson}
          @input=${(event: Event) => {
            this._pasteJson = (event.target as HTMLTextAreaElement).value;
          }}>
        </uui-textarea>
        <uui-button
          look="primary"
          label="Import the pasted JSON"
          ?disabled=${this._importing || !this._pasteJson.trim()}
          @click=${this.#importPasted}>
          Import
        </uui-button>
      </div>
    `;
  }

  #renderEmpty() {
    return html`
      <div class="empty">
        <uui-icon name="icon-brush"></uui-icon>
        <h4>No templates yet</h4>
        <p>A template says which document types get a generated image, and what it looks like.</p>
        <uui-button look="primary" color="positive" href=${hrefForCreate()} label="Create your first template">
          Create your first template
        </uui-button>
      </div>
    `;
  }

  #renderCards() {
    return html`
      <div class="cards">
        ${repeat(
          this._templates,
          (template) => template.key,
          (template) => html`
            <uui-box class="card ${template.isEnabled ? "" : "disabled"}">
              <div slot="headline">
                <a href=${hrefForTemplate(template.key)}>${template.name}</a>
                ${template.isEnabled ? nothing : html`<uui-tag look="secondary">Disabled</uui-tag>`}
              </div>

              <dl>
                <dt>Applies to</dt>
                <dd>${template.docTypeAliases.join(", ") || "Nothing yet"}</dd>
                <dt>Writes to</dt>
                <dd>${template.targetPropertyAlias || "Nothing yet"}</dd>
                <dt>Canvas</dt>
                <dd>${template.canvasWidth} × ${template.canvasHeight}, ${template.layerCount} layer(s)</dd>
              </dl>

              <div class="card-actions">
                <uui-button look="secondary" href=${hrefForTemplate(template.key)} label="Design ${template.name}">
                  Design
                </uui-button>
                <uui-button look="secondary" label="Duplicate ${template.name}" @click=${() => this.#duplicate(template)}>
                  Duplicate
                </uui-button>
                <uui-button look="secondary" label="Export ${template.name}" @click=${() => this.#export(template)}>
                  Export
                </uui-button>
                <uui-button
                  look="secondary"
                  color="danger"
                  label="Delete ${template.name}"
                  @click=${() => this.#delete(template)}>
                  Delete
                </uui-button>
              </div>
            </uui-box>
          `,
        )}
      </div>
    `;
  }

  static styles = css`
    :host {
      display: block;
    }

    .state {
      display: flex;
      justify-content: center;
      padding: var(--uui-size-layout-3);
    }

    uui-box {
      margin-bottom: var(--uui-size-layout-1);
    }

    .stats {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: var(--uui-size-space-4);
      margin-bottom: var(--uui-size-layout-1);
    }

    .stat {
      text-align: center;
    }

    .stat.warn {
      border-left: 3px solid var(--uui-color-warning);
    }

    .stat-value {
      font-size: 2rem;
      font-weight: 700;
      line-height: 1.1;
    }

    .stat-label {
      color: var(--uui-color-text-alt);
      font-size: 0.85rem;
    }

    .header-actions {
      display: flex;
      gap: var(--uui-size-space-3);
    }

    .paste {
      display: grid;
      gap: var(--uui-size-space-3);
      margin-bottom: var(--uui-size-layout-1);
    }

    .cards {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
      gap: var(--uui-size-space-4);
    }

    .card.disabled {
      opacity: 0.7;
    }

    .card a {
      color: inherit;
      text-decoration: none;
    }

    .card a:hover {
      text-decoration: underline;
    }

    dl {
      display: grid;
      grid-template-columns: auto 1fr;
      gap: var(--uui-size-space-1) var(--uui-size-space-4);
      margin: 0 0 var(--uui-size-space-4);
      font-size: 0.9rem;
    }

    dt {
      color: var(--uui-color-text-alt);
    }

    dd {
      margin: 0;
    }

    .card-actions {
      display: flex;
      flex-wrap: wrap;
      gap: var(--uui-size-space-2);
    }

    .empty {
      text-align: center;
      padding: var(--uui-size-layout-2);
      color: var(--uui-color-text-alt);
    }

    .empty uui-icon {
      font-size: 2.5rem;
    }

    .empty h4 {
      margin: var(--uui-size-space-3) 0 var(--uui-size-space-2);
      color: var(--uui-color-text);
    }

    @media (max-width: 720px) {
      .cards {
        grid-template-columns: 1fr;
      }
    }
  `;
}

export default DiOverviewDashboardElement;

declare global {
  interface HTMLElementTagNameMap {
    "di-overview-dashboard": DiOverviewDashboardElement;
  }
}
