using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.Formats.Webp;
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.IO;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.PropertyEditors;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Strings;
using Umbraco.Community.DynamicImages.Core.Models;
using Umbraco.Extensions;
using Template = Umbraco.Community.DynamicImages.Core.Models.Template;

namespace Umbraco.Community.DynamicImages.Core.Media;

public sealed class DynamicImageMediaWriter(
    IMediaService mediaService,
    IRelationService relationService,
    MediaFileManager mediaFileManager,
    MediaUrlGeneratorCollection mediaUrlGenerators,
    IShortStringHelper shortStringHelper,
    IContentTypeBaseServiceProvider contentTypeBaseServiceProvider,
    ILogger<DynamicImageMediaWriter> logger) : IDynamicImageMediaWriter
{
    public async Task<Guid> WriteAsync(
        Image image,
        Template template,
        IContent content,
        Guid? existingMediaKey,
        CancellationToken cancellationToken = default)
    {
        var bytes = await EncodeAsync(image, template.Output, cancellationToken);
        var mediaName = BuildName(template, content.Name ?? template.Name);
        var fileName = $"{mediaName.ToSafeFileName(shortStringHelper)}{ExtensionFor(template.Output.Format)}";

        // Replacing in place keeps the media key, and therefore every MediaPicker reference and
        // shared URL pointing at it, valid across regenerations - but only for an image this
        // package generated. The target property is an ordinary media picker, and an editor may
        // well have hand-picked a shared hero or logo into it; overwriting that file would
        // replace it everywhere else it is used too.
        var existing = existingMediaKey is null ? null : mediaService.GetById(existingMediaKey.Value);
        var media = Reusable(existing, content, template, mediaName) ? existing : null;
        var created = media is null;

        if (media is null)
        {
            var parentId = ResolveFolderId(template.Output.MediaFolderKey);
            media = mediaService.CreateMedia(mediaName, parentId, Constants.Conventions.MediaTypes.Image);
        }
        else
        {
            media.Name = mediaName;
        }

        using var stream = new MemoryStream(bytes);
        media.SetValue(
            mediaFileManager,
            mediaUrlGenerators,
            shortStringHelper,
            contentTypeBaseServiceProvider,
            Constants.Conventions.Media.File,
            fileName,
            stream);

        mediaService.Save(media);

        // After the save, because a new media item has no id to relate until it has one. Relating
        // an item that was matched by the legacy rule below is what makes the relation
        // authoritative from the second write onwards.
        Relate(content, media);

        if (created && existing is not null)
        {
            logger.LogInformation(
                "Dynamic Images: media {MediaKey} was not generated by this package, so a new image was created for '{ContentName}' rather than overwriting it",
                existingMediaKey, content.Name);
        }

        return media.Key;
    }

    /// <summary>
    /// Whether the existing media item is one this package may overwrite in place: an image, and
    /// either already related to this document as a generated image or matching the legacy shape
    /// an image generated before the relation existed would have.
    /// </summary>
    private bool Reusable(IMedia? existing, IContent content, Template template, string mediaName)
    {
        if (existing is null) return false;

        if (!string.Equals(existing.ContentType.Alias, Constants.Conventions.MediaTypes.Image, StringComparison.OrdinalIgnoreCase))
        {
            // Whatever that key points at, it is not something we may overwrite.
            logger.LogWarning(
                "Dynamic Images: media {MediaKey} is a '{Alias}', not an image, so a new media item was created instead",
                existing.Key, existing.ContentType.Alias);

            return false;
        }

        if (AreRelated(content, existing)) return true;

        // Upgrade path: images generated before the relation existed carry no marker, and the
        // first regeneration after upgrading must not orphan them. An image sitting in this
        // template's output folder under exactly the name this template would give it is one of
        // ours; the write relates it, after which the relation alone decides.
        return existing.ParentId == ResolveFolderId(template.Output.MediaFolderKey)
            && string.Equals(existing.Name, mediaName, StringComparison.Ordinal);
    }

    private bool AreRelated(IContent content, IMedia media)
    {
        try
        {
            return relationService.AreRelated(content, media, DynamicImagesConstants.GeneratedImageRelationAlias);
        }
        catch (Exception ex)
        {
            // The relation type is installed by a migration. A site part-way through an upgrade,
            // or one whose relation type was deleted by hand, should keep generating images -
            // falling back to "not related" means a new media item, never someone else's file.
            logger.LogWarning(ex, "Dynamic Images: could not read the generated-image relation; treating the image as not ours");
            return false;
        }
    }

    private void Relate(IContent content, IMedia media)
    {
        try
        {
            if (relationService.AreRelated(content, media, DynamicImagesConstants.GeneratedImageRelationAlias)) return;

            relationService.Relate(content, media, DynamicImagesConstants.GeneratedImageRelationAlias);
        }
        catch (Exception ex)
        {
            // The image is already written and saved by this point. Losing the marker costs a new
            // media item on the next regeneration; failing here would cost the editor their image.
            logger.LogWarning(ex,
                "Dynamic Images: the image for '{ContentName}' was saved but could not be marked as generated by this package",
                content.Name);
        }
    }

    public async Task<byte[]> EncodeAsync(Image image, OutputSettings output, CancellationToken cancellationToken = default)
    {
        using var stream = new MemoryStream();
        var quality = Math.Clamp(output.Quality, 1, 100);

        // The encoder and the file extension come from the same setting, so a generated image is
        // never served with the wrong type.
        switch (output.Format)
        {
            case OutputFormat.Jpeg:
                await image.SaveAsJpegAsync(stream, new JpegEncoder { Quality = quality }, cancellationToken);
                break;

            case OutputFormat.Webp:
                await image.SaveAsWebpAsync(stream, new WebpEncoder { Quality = quality }, cancellationToken);
                break;

            default:
                await image.SaveAsPngAsync(stream, new PngEncoder(), cancellationToken);
                break;
        }

        return stream.ToArray();
    }

    public string ExtensionFor(OutputFormat format) => format switch
    {
        OutputFormat.Jpeg => ".jpg",
        OutputFormat.Webp => ".webp",
        _ => ".png"
    };

    public string ContentTypeFor(OutputFormat format) => format switch
    {
        OutputFormat.Jpeg => "image/jpeg",
        OutputFormat.Webp => "image/webp",
        _ => "image/png"
    };

    /// <summary>Applies the template's file name pattern: {name}, {template}.</summary>
    private static string BuildName(Template template, string contentName)
    {
        var pattern = string.IsNullOrWhiteSpace(template.Output.FileNamePattern) ? "{name}" : template.Output.FileNamePattern;

        var name = pattern
            .Replace("{name}", contentName, StringComparison.OrdinalIgnoreCase)
            .Replace("{template}", template.Alias, StringComparison.OrdinalIgnoreCase)
            .Trim();

        return string.IsNullOrWhiteSpace(name) ? contentName : name;
    }

    private int ResolveFolderId(Guid? folderKey)
    {
        if (folderKey is null) return Constants.System.Root;

        var folder = mediaService.GetById(folderKey.Value);

        if (folder is null)
        {
            logger.LogWarning("Dynamic Images: output folder {FolderKey} no longer exists; saving to the media root", folderKey);
            return Constants.System.Root;
        }

        // Creating an image under another image is not valid media structure, and the backoffice
        // media picker cannot filter to folders reliably - so it is checked here instead.
        if (!string.Equals(folder.ContentType.Alias, Constants.Conventions.MediaTypes.Folder, StringComparison.OrdinalIgnoreCase))
        {
            logger.LogWarning(
                "Dynamic Images: output folder {FolderKey} is a '{Alias}', not a folder; saving to the media root",
                folderKey, folder.ContentType.Alias);

            return Constants.System.Root;
        }

        return folder.Id;
    }
}
